/*
 * stu_rtmp_message.h
 *
 *  Created on: 2018骞�1鏈�16鏃�
 *      Author: Tony Lau
 */

#ifndef STUDEASE_CN_RTMP_STU_RTMP_MESSAGE_H_
#define STUDEASE_CN_RTMP_STU_RTMP_MESSAGE_H_

#include "stu_rtmp.h"

#define STU_RTMP_MESSAGE_TYPE_SET_CHUNK_SIZE      0x01
#define STU_RTMP_MESSAGE_TYPE_ABORT               0x02
#define STU_RTMP_MESSAGE_TYPE_ACK                 0x03
#define STU_RTMP_MESSAGE_TYPE_USER_CONTROL        0x04
#define STU_RTMP_MESSAGE_TYPE_ACK_WINDOW_SIZE     0x05
#define STU_RTMP_MESSAGE_TYPE_BANDWIDTH           0x06
#define STU_RTMP_MESSAGE_TYPE_EDGE                0x07
#define STU_RTMP_MESSAGE_TYPE_AUDIO               0x08
#define STU_RTMP_MESSAGE_TYPE_VIDEO               0x09
#define STU_RTMP_MESSAGE_TYPE_AMF3_DATA           0x0F
#define STU_RTMP_MESSAGE_TYPE_AMF3_SHARED_OBJECT  0x10
#define STU_RTMP_MESSAGE_TYPE_AMF3_COMMAND        0x11
#define STU_RTMP_MESSAGE_TYPE_DATA                0x12
#define STU_RTMP_MESSAGE_TYPE_SHARED_OBJECT       0x13
#define STU_RTMP_MESSAGE_TYPE_COMMAND             0x14
#define STU_RTMP_MESSAGE_TYPE_AGGREGATE           0x16

#define STU_RTMP_EVENT_TYPE_STREAM_BEGIN          0x0000
#define STU_RTMP_EVENT_TYPE_STREAM_EOF            0x0001
#define STU_RTMP_EVENT_TYPE_STREAM_DRY            0x0002
#define STU_RTMP_EVENT_TYPE_SET_BUFFER_LENGTH     0x0003
#define STU_RTMP_EVENT_TYPE_STREAM_IS_RECORDED    0x0004
#define STU_RTMP_EVENT_TYPE_PING_REQUEST          0x0006
#define STU_RTMP_EVENT_TYPE_PING_RESPONSE         0x0007

#define STU_RTMP_BANDWIDTH_LIMIT_TYPE_HARD        0x00
#define STU_RTMP_BANDWIDTH_LIMIT_TYPE_SOFT        0x01
#define STU_RTMP_BANDWIDTH_LIMIT_TYPE_DYNAMIC     0x02

#define STU_RTMP_AUDIO_CODEC_LINEAR_PCM_PLATFORM_ENDIAN    0x00
#define STU_RTMP_AUDIO_CODEC_ADPCM                         0x01
#define STU_RTMP_AUDIO_CODEC_MP3                           0x02
#define STU_RTMP_AUDIO_CODEC_LINEAR_PCM_LITTLE_ENDIAN      0x03
#define STU_RTMP_AUDIO_CODEC_NELLYMOSER_16_kHz_MONO        0x04
#define STU_RTMP_AUDIO_CODEC_NELLYMOSER_8_kHz_MONO         0x05
#define STU_RTMP_AUDIO_CODEC_NELLYMOSER                    0x06
#define STU_RTMP_AUDIO_CODEC_G_711_A_LAW_LOGARITHMIC_PCM   0x07
#define STU_RTMP_AUDIO_CODEC_G_711_MU_LAW_LOGARITHMIC_PCM  0x08
#define STU_RTMP_AUDIO_CODEC_RESERVED                      0x09
#define STU_RTMP_AUDIO_CODEC_AAC                           0x0A
#define STU_RTMP_AUDIO_CODEC_SPEEX                         0x0B
#define STU_RTMP_AUDIO_CODEC_MP3_8_kHz                     0x0E
#define STU_RTMP_AUDIO_CODEC_DEVICE_SPECIFIC_SOUND         0x0F

#define STU_RTMP_VIDEO_CODEC_JPEG                          0x01
#define STU_RTMP_VIDEO_CODEC_H263                          0x02
#define STU_RTMP_VIDEO_CODEC_SCREEN_VIDEO                  0x03
#define STU_RTMP_VIDEO_CODEC_VP6                           0x04
#define STU_RTMP_VIDEO_CODEC_VP6_ALPHA                     0x05
#define STU_RTMP_VIDEO_CODEC_SCREEN_VIDEO_2                0x06
#define STU_RTMP_VIDEO_CODEC_AVC                           0x07

extern stu_str_t  STU_RTMP_CMD_CONNECT;
extern stu_str_t  STU_RTMP_CMD_CLOSE;
extern stu_str_t  STU_RTMP_CMD_CREATE_STREAM;
extern stu_str_t  STU_RTMP_CMD_RESULT;
extern stu_str_t  STU_RTMP_CMD_ERROR;

extern stu_str_t  STU_RTMP_CMD_PLAY;
extern stu_str_t  STU_RTMP_CMD_PLAY2;
extern stu_str_t  STU_RTMP_CMD_DELETE_STREAM;
extern stu_str_t  STU_RTMP_CMD_CLOSE_STREAM;
extern stu_str_t  STU_RTMP_CMD_RECEIVE_AUDIO;
extern stu_str_t  STU_RTMP_CMD_RECEIVE_VIDEO;
extern stu_str_t  STU_RTMP_CMD_PUBLISH;
extern stu_str_t  STU_RTMP_CMD_SEEK;
extern stu_str_t  STU_RTMP_CMD_PAUSE;
extern stu_str_t  STU_RTMP_CMD_ON_STATUS;

// outdated
extern stu_str_t  STU_RTMP_CMD_RELEASE_STREAM;
extern stu_str_t  STU_RTMP_CMD_FC_PUBLISH;
extern stu_str_t  STU_RTMP_CMD_ON_FC_PUBLISH;

extern stu_str_t  STU_RTMP_SET_DATA_FRAME;
extern stu_str_t  STU_RTMP_CLEAR_DATA_FRAME;
extern stu_str_t  STU_RTMP_ON_META_DATA;

extern stu_str_t  STU_RTMP_LEVEL;
extern stu_str_t  STU_RTMP_CODE;
extern stu_str_t  STU_RTMP_DESCRIPTION;

extern stu_str_t  STU_RTMP_LEVEL_ERROR;
extern stu_str_t  STU_RTMP_LEVEL_STATUS;
extern stu_str_t  STU_RTMP_LEVEL_WARNING;

extern stu_str_t  STU_RTMP_PUBLISHING_TYPE_LIVE;
extern stu_str_t  STU_RTMP_PUBLISHING_TYPE_RECORD;
extern stu_str_t  STU_RTMP_PUBLISHING_TYPE_APPEND;
extern stu_str_t  STU_RTMP_PUBLISHING_TYPE_APPEND_WITH_GAP;

extern stu_str_t  STU_RTMP_CODE_NETCONNECTION_CALL_FAILED;
extern stu_str_t  STU_RTMP_CODE_NETCONNECTION_CONNECT_APPSHUTDOWN;
extern stu_str_t  STU_RTMP_CODE_NETCONNECTION_CONNECT_CLOSED;
extern stu_str_t  STU_RTMP_CODE_NETCONNECTION_CONNECT_FAILED;
extern stu_str_t  STU_RTMP_CODE_NETCONNECTION_CONNECT_IDLETIMEOUT;
extern stu_str_t  STU_RTMP_CODE_NETCONNECTION_CONNECT_INVALIDAPP;
extern stu_str_t  STU_RTMP_CODE_NETCONNECTION_CONNECT_REJECTED;
extern stu_str_t  STU_RTMP_CODE_NETCONNECTION_CONNECT_SUCCESS;

extern stu_str_t  STU_RTMP_CODE_NETSTREAM_BUFFER_EMPTY;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_BUFFER_FLUSH;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_BUFFER_FULL;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_FAILED;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_PAUSE_NOTIFY;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_PLAY_FAILED;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_PLAY_FILESTRUCTUREINVALID;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_PLAY_PUBLISHNOTIFY;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_PLAY_RESET;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_PLAY_START;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_PLAY_STOP;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_PLAY_STREAMNOTFOUND;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_PLAY_UNPUBLISHNOTIFY;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_PUBLISH_BADNAME;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_PUBLISH_IDLE;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_PUBLISH_START;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_RECORD_ALREADYEXISTS;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_RECORD_FAILED;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_RECORD_NOACCESS;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_RECORD_START;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_RECORD_STOP;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_SEEK_FAILED;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_SEEK_INVALIDTIME;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_SEEK_NOTIFY;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_STEP_NOTIFY;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_UNPAUSE_NOTIFY;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_UNPUBLISH_SUCCESS;
extern stu_str_t  STU_RTMP_CODE_NETSTREAM_VIDEO_DIMENSIONCHANGE;

stu_int32_t  stu_rtmp_message_init();

#endif /* STUDEASE_CN_RTMP_STU_RTMP_MESSAGE_H_ */
